spring.application.name=CourtReseve

jwt.secret= C1dM8PAxF2oCgp2Y0bUY6N1neW3dOVE7IKGDBm7UbZo=
jwt.issuer=courtreserve
jwt.access-token-expiration-minutes=15
jwt.refresh-token-expiration-days=7

jwt.refresh-cookie-name=refresh_token
jwt.refresh-cookie-path=/api/auth
jwt.refresh-cookie-secure=true
jwt.refresh-cookie-same-site=Strict